/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    voitures: Voiture;
    marques: Marque;
    categories: Categorie;
    media: Media;
    demandes: Demande;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    voitures: VoituresSelect<false> | VoituresSelect<true>;
    marques: MarquesSelect<false> | MarquesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    demandes: DemandesSelect<false> | DemandesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    agence: Agence;
    apparence: ReglagesApparence;
    mails: ReglagesMails;
    'pages-legales': PagesLegales;
    securite: ReglagesSecurite;
  };
  globalsSelect: {
    agence: AgenceSelect<false> | AgenceSelect<true>;
    apparence: ApparenceSelect<false> | ApparenceSelect<true>;
    mails: MailsSelect<false> | MailsSelect<true>;
    'pages-legales': PagesLegalesSelect<false> | PagesLegalesSelect<true>;
    securite: SecuriteSelect<false> | SecuriteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voitures".
 */
export interface Voiture {
  id: string;
  /**
   * À louer : tarifs de location. À vendre : prix de vente, année et kilométrage.
   */
  offre: 'location' | 'vente';
  /**
   * Marque absente de la liste ? Ajoutez-la avec le bouton + à droite du champ.
   */
  marque: string | Marque;
  modele: string;
  /**
   * S’il est rempli, c’est ce nom qui s’affiche partout sur le site. Sinon : marque + modèle. L’adresse de la page ne change pas.
   */
  nomComplet?: string | null;
  categorie: string | Categorie;
  /**
   * La première photo est la photo principale.
   */
  photos: (string | Media)[];
  /**
   * Facultatif. Photographiez la voiture en tournant autour, du même endroit et à la même hauteur : 24 à 36 photos, dans l’ordre. Le visiteur pourra la faire tourner au doigt. En dessous de 8 photos, le tour ne s’affiche pas.
   */
  tour360?: (string | Media)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  caracteristiques: {
    boite: 'manuelle' | 'automatique';
    carburant: 'essence' | 'diesel' | 'hybride' | 'electrique';
    places: number;
    portes?: number | null;
    climatisation?: boolean | null;
  };
  vente?: {
    prix?: number | null;
    annee?: number | null;
    kilometrage?: number | null;
  };
  tarifs?: {
    prixJour?: number | null;
    prixWeekend?: number | null;
    prixSemaine?: number | null;
    caution?: number | null;
    kmInclus?: string | null;
  };
  /**
   * Décochez quand la voiture est louée : elle reste affichée avec un badge « Déjà louée ».
   */
  disponible?: boolean | null;
  /**
   * Rempli automatiquement (marque + modèle).
   */
  titre?: string | null;
  /**
   * Généré automatiquement à la création, ne change plus ensuite.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * La liste proposée dans le formulaire d’une voiture. Ajoutez ici les marques qui manquent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marques".
 */
export interface Marque {
  id: string;
  nom: string;
  /**
   * Généré automatiquement à la création, ne change plus ensuite.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Categorie {
  id: string;
  nom: string;
  /**
   * Généré automatiquement à la création, ne change plus ensuite.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    carte?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    grande?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tour?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes".
 */
export interface Demande {
  id: string;
  prenom: string;
  nom: string;
  email: string;
  telephone: string;
  adresse: {
    rue: string;
    codePostal: string;
    ville: string;
  };
  /**
   * Vide = question générale.
   */
  voiture?: (string | null) | Voiture;
  message: string;
  /**
   * Déduite de l’offre de la voiture au moment de la demande.
   */
  nature?: ('location' | 'vente' | 'generale') | null;
  statut: 'nouvelle' | 'traitee';
  mailAgenceEnvoye?: boolean | null;
  mailClientEnvoye?: boolean | null;
  /**
   * Rempli automatiquement.
   */
  titre?: string | null;
  /**
   * Sert à limiter le nombre de demandes par heure. L’adresse IP n’est pas conservée : ceci en est une version brouillée, impossible à retrouver.
   */
  empreinteIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  codeAuthEmpreinte?: string | null;
  codeAuthExpiration?: string | null;
  codeAuthTentatives?: number | null;
  jetonEnAttente?: string | null;
  identifiantAttente?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'voitures';
        value: string | Voiture;
      } | null)
    | ({
        relationTo: 'marques';
        value: string | Marque;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Categorie;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'demandes';
        value: string | Demande;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "voitures_select".
 */
export interface VoituresSelect<T extends boolean = true> {
  offre?: T;
  marque?: T;
  modele?: T;
  nomComplet?: T;
  categorie?: T;
  photos?: T;
  tour360?: T;
  description?: T;
  caracteristiques?:
    | T
    | {
        boite?: T;
        carburant?: T;
        places?: T;
        portes?: T;
        climatisation?: T;
      };
  vente?:
    | T
    | {
        prix?: T;
        annee?: T;
        kilometrage?: T;
      };
  tarifs?:
    | T
    | {
        prixJour?: T;
        prixWeekend?: T;
        prixSemaine?: T;
        caution?: T;
        kmInclus?: T;
      };
  disponible?: T;
  titre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marques_select".
 */
export interface MarquesSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        carte?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        grande?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tour?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes_select".
 */
export interface DemandesSelect<T extends boolean = true> {
  prenom?: T;
  nom?: T;
  email?: T;
  telephone?: T;
  adresse?:
    | T
    | {
        rue?: T;
        codePostal?: T;
        ville?: T;
      };
  voiture?: T;
  message?: T;
  nature?: T;
  statut?: T;
  mailAgenceEnvoye?: T;
  mailClientEnvoye?: T;
  titre?: T;
  empreinteIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  codeAuthEmpreinte?: T;
  codeAuthExpiration?: T;
  codeAuthTentatives?: T;
  jetonEnAttente?: T;
  identifiantAttente?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agence".
 */
export interface Agence {
  id: string;
  nom?: string | null;
  accroche?: string | null;
  sousAccroche?: string | null;
  adresse?: {
    rue?: string | null;
    codePostal?: string | null;
    ville?: string | null;
  };
  telephone?: string | null;
  emailPublic?: string | null;
  horaires?:
    | {
        jours: string;
        heures: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facultatif : sans logo, le nom de l’agence s’affiche en texte.
   */
  logo?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Le décor animé du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparence".
 */
export interface ReglagesApparence {
  id: string;
  /**
   * Facultatif. Les vues d’une voiture prises tout autour, dans l’ordre : elle tournera en fond de page pendant que le visiteur descend. En dessous de 8 vues, le décor ne s’affiche pas. Cette voiture n’apparaît nulle part dans le catalogue.
   */
  decor360?: (string | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Qui est prévenu quand un visiteur envoie le formulaire de contact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mails".
 */
export interface ReglagesMails {
  id: string;
  /**
   * Chaque demande part vers toutes ces adresses. Sans aucune adresse, la demande reste enregistrée dans « Demandes » mais n’est transmise à personne.
   */
  destinataires?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facultatif : reçoit une copie de chaque demande sans apparaître dans le mail.
   */
  copieCachee?: string | null;
  /**
   * Au-delà, la demande est refusée avec un message. Vide = 10.
   */
  limiteParHeure?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales".
 */
export interface PagesLegales {
  id: string;
  mentionsLegales?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  confidentialite?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Comment on entre dans l’administration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "securite".
 */
export interface ReglagesSecurite {
  id: string;
  /**
   * Après le mot de passe, un code à 6 chiffres est envoyé par email et doit être saisi. Il est valable 10 minutes. En cas de blocage (plus accès à la boîte mail), lancer « npm run 2fa:off » depuis le dossier du projet.
   */
  doubleAuth?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agence_select".
 */
export interface AgenceSelect<T extends boolean = true> {
  nom?: T;
  accroche?: T;
  sousAccroche?: T;
  adresse?:
    | T
    | {
        rue?: T;
        codePostal?: T;
        ville?: T;
      };
  telephone?: T;
  emailPublic?: T;
  horaires?:
    | T
    | {
        jours?: T;
        heures?: T;
        id?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparence_select".
 */
export interface ApparenceSelect<T extends boolean = true> {
  decor360?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mails_select".
 */
export interface MailsSelect<T extends boolean = true> {
  destinataires?:
    | T
    | {
        email?: T;
        id?: T;
      };
  copieCachee?: T;
  limiteParHeure?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales_select".
 */
export interface PagesLegalesSelect<T extends boolean = true> {
  mentionsLegales?: T;
  confidentialite?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "securite_select".
 */
export interface SecuriteSelect<T extends boolean = true> {
  doubleAuth?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}